### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by dara1429** [Frontman113/Final-Project#1]
Choosing option 1 (Areas) results in a seg fault.

My exact commands:
*run*
test
5
Goodbye
1
*segmentation fault*

Here is what happens when i choose areas.
1:Church-->Car Dealership***Restaurant***Country Club
2:Bar-->Frat House***Mall***Campus
2:Gym-->Frat House
1:Car Dealership-->Church***Hospital***Highway
2:Frat House-->Bar***Gym***Mall
2:Mall-->Bar***Frat House
1:Whole Foods-->Hospital***Lake
1:Theater-->Restaurant
1:Restaurant-->Church***Theater***Country Club
1:Country Club-->Church***Restaurant
2:Campus-->Bar
1:Hospital-->Car Dealership***Whole Foods***Lake***Prison***Highway
1:Lake-->Whole Foods***Hospital
1:Prison-->Hospital***Highway
Segmentation fault (core dumped)
user@cu-cs-vm:~/Dropbox/Final-Project$

**Comment by Frontman113** [comment]
Do you have any more information? no matter how many times I run the
commands you specified the program runs properly for me.

**Comment by dara1429** [comment]
It may have something to do with the compiler settings because i had a similar where someone was having seg faults even when my code worked fine. I think i found a fix for it. Ill try it on your code today and get back to you.

**Comment by dara1429** [comment]
Yeah it is still seg. faulting whenever i try and list the areas. Everything else works fine so far. Not sure whats happening. It does not like accessing the last node in your graph.
![screenshot - 04302015 - 01-13-31 pm](https://cloud.githubusercontent.com/assets/11980947/7420621/2401b24e-ef3b-11e4-9453-8de835b19f53.png)

**Comment by Frontman113** [comment]
I see. The prison is the last node in the graph. I'll make sure the
zombies.txt doesn't have anything weird in it on github. Thanks for your
assistance
